force-app/main/default/objects/Sync_Log__c/Sync_Log__c.object-meta.xml
<CustomObject>
    <description>APAL VMAP Sycn Logs</description>
    <label>Sync Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Sync Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log__c/fields/Account_Provider_Practice__c.field-meta.xml
<CustomField>
    <fullName>Account_Provider_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Account</description>
    <inlineHelpText>Related Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sync Logs</relationshipLabel>
    <relationshipName>Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Data_Payload_Json__c.field-meta.xml
<CustomField>
    <fullName>Data_Payload_Json__c</fullName>
    <description>Json with Payload for Sync</description>
    <inlineHelpText>Json with Payload for Sync</inlineHelpText>
    <label>Data Payload (Json)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Sync Error Message</description>
    <inlineHelpText>Sync Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/External_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>External_Account_ID__c</fullName>
    <description>Account External ID to Match Accounts in VMAP and APAL

ID Identifies when and where the account was created  first.</description>
    <label>Sync Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/LastAttempted__c.field-meta.xml
<CustomField>
    <fullName>LastAttempted__c</fullName>
    <description>Date/Time of last Sync Attempt</description>
    <inlineHelpText>Date/Time of last Sync Attempt</inlineHelpText>
    <label>Last Attempted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Stores the detailed execution trace of an error, capturing the sequence of method calls leading to the exception. This field helps in debugging by providing insights into where and why an issue occurred in the code execution flow.</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Sync Status
In Process = New
Complete = Closed/Finish
Retry =  Run Retry attempts
Failed = Stop</description>
    <inlineHelpText>Sync Status
In Process = New
Complete = Closed/Finish
Retry =  Run Retry attempts
Failed = Stop</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Sync_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sync_Direction__c</fullName>
    <description>Direction of Sync: Show where and to what instance sync is initiated.</description>
    <inlineHelpText>Direction of Sync, showing where to what instance sync is initiated.</inlineHelpText>
    <label>Sync Direction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VMAP</fullName>
                <label>APAL → VMAP</label>
            </value>
            <value>
                <fullName>APAL</fullName>
                <label>VMAP → APAL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Sync_Initiator__c.field-meta.xml
<CustomField>
    <fullName>Sync_Initiator__c</fullName>
    <description>Identifies the user or process that initiated the synchronization.</description>
    <label>Sync Initiator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Sync_Initiator_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sync_Initiator_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sync Initiator Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sync_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/fields/Sync_Type__c.field-meta.xml
<CustomField>
    <fullName>Sync_Type__c</fullName>
    <description>Indicates the type of synchronization operation recorded in the Sync Log. This field helps track whether a record was newly created or updated during the sync process.</description>
    <label>Sync Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CREATE</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountSyncLoggerApal.cls
public without sharing  class AccountSyncLoggerApal {
    @TestVisible
    private static final String LOG_STATUS_COMPLETE = 'Complete';
    @TestVisible
    private static final String LOG_STATUS_FAILED = 'Failed';

    private static final String DEBUG_MESSAGE_TEMPLATE = '{0}: {1}';

    private static AccountSyncLoggerApal syncLogger;

    public static AccountSyncLoggerApal getInstance() {
        if (syncLogger == null) {
            syncLogger = new AccountSyncLoggerApal();
        }
        return syncLogger;
    }

    public LogInstance createCompleteLog() {
        return this.createLog(LOG_STATUS_COMPLETE);
    }

    public LogInstance createFailedLog(HttpResponse response, AccountChangeEvent accountChangeEvent, String syncId) {
        try {
            return new LogInstance((Sync_Log__c) JSON.deserialize(
                    response.getBody().toString(), Sync_Log__c.class
            ));
        } catch (Exception ex) {
            return this.createLog(LOG_STATUS_FAILED)
                    .setError(response.getBody().toString())
                    .setSyncId(syncId)
                    .setRecordId(accountChangeEvent.ChangeEventHeader.getRecordIds()[0])
                    .setType(accountChangeEvent.ChangeEventHeader.getChangeType())
                    .setInitiator(AccountSyncUtilApal.getCommitUser(accountChangeEvent))
                    .setDirection(AccountSyncUtilApal.APAL_PREFIX)
                    .setPayload(accountChangeEvent);
        }
    }

    public LogInstance createFailedLog(Exception ex) {
        return this.createLog(LOG_STATUS_FAILED)
                .setError(ex.getMessage())
                .setStackTrace(ex.getStackTraceString());
    }

    public void commitLog(LogInstance logInstance) {
        this.commitLogs(new List<LogInstance>{
                logInstance
        });
    }

    public void commitLogs(List<LogInstance> logInstances) {
        List<Sync_Log__c> syncLogs = new List<Sync_Log__c>();
        for (LogInstance logInstance : logInstances) {
            syncLogs.add(logInstance.log);
        }
        try {
            if (syncLogs != null && !syncLogs.isEmpty()) {
                Database.insert(syncLogs);
            }
        } catch (Exception ex) {
            this.setDebug(AccountSyncUtilApal.DEBUG_HEADER_EXCEPTION_MESSAGE, ex.getMessage());
        }
    }

    public void setDebug(String debugHeader, Object debugValue) {
        this.setDebug(debugHeader, JSON.serializePretty(debugValue));
    }

    public void setDebug(String debugHeader, String debugValue) {
        System.debug(
                LoggingLevel.INFO,
                String.format(DEBUG_MESSAGE_TEMPLATE, new List<String>{
                        debugHeader, debugValue
                })
        );
    }

    public LogInstance logSyncResponse(HttpResponse synResponse, AccountChangeEvent accountChangeEvent, String syncId) {
        LogInstance synResponseLog;
        if (synResponse.getStatusCode() == CalloutService.STATUS_CODE_200) {
            synResponseLog = this.createCompleteLog()
                    .setSyncId(syncId)
                    .setRecordId(Id.valueOf(accountChangeEvent.ChangeEventHeader.getRecordIds()[0]))
                    .setType(accountChangeEvent.ChangeEventHeader.getChangeType())
                    .setInitiator(AccountSyncUtilApal.getCommitUser(accountChangeEvent))
                    .setDirection(AccountSyncUtilApal.APAL_PREFIX)
                    .setPayload(accountChangeEvent);
        } else {
            synResponseLog = this.createFailedLog(synResponse, accountChangeEvent, syncId)
                    .setRecordId(Id.valueOf(accountChangeEvent.ChangeEventHeader.getRecordIds()[0]))
                    .setInitiator(AccountSyncUtilApal.getCommitUser(accountChangeEvent));
        }
        return synResponseLog;
    }

    private LogInstance createLog(String logStatus) {
        return new LogInstance(logStatus);
    }

    public class LogInstance {

        public Sync_Log__c log;

        public LogInstance(Sync_Log__c log) {
            this.log = log;
        }
        public LogInstance(String logStatus) {
            this.log = new Sync_Log__c(
                    Status__c = logStatus,
                    LastAttempted__c = Datetime.now()
            );
        }

        public LogInstance setSyncId(String syncId) {
            this.log.External_Account_ID__c = syncId;
            return this;
        }

        public LogInstance setRecordId(Id recordId) {
            this.log.Account_Provider_Practice__c = recordId;
            return this;
        }

        public LogInstance setError(String errorMessage) {
            this.log.Error_Message__c = errorMessage.length() > 255 ? errorMessage.substring(0, 255) : errorMessage;
            return this;
        }
        public LogInstance setStackTrace(String stackTrace) {
            this.log.Stack_Trace__c = stackTrace;
            return this;
        }
        public LogInstance setPayload(String payload) {
            this.log.Data_Payload_Json__c = JSON.serializePretty(JSON.deserializeUntyped(payload));
            return this;
        }

        public LogInstance setPayload(Object payload) {
            this.log.Data_Payload_Json__c = JSON.serializePretty(payload);
            return this;
        }

        public LogInstance setDirection(String direction) {
            this.log.Sync_Direction__c = direction.toUpperCase();
            return this;
        }

        public LogInstance setType(String type) {
            this.log.Sync_Type__c = type;
            return this;
        }

        public LogInstance setInitiator(String initiatorName) {
            this.log.Sync_Initiator__c = initiatorName;
            return this;
        }

        public LogInstance setInitiator(User initiator) {
            this.log.Sync_Initiator__c = initiator?.Name;
            this.log.Sync_Initiator_Lookup__c = initiator?.Id;
            return this;
        }
    }
}