force-app/main/default/objects/Account/fields/On_Demand_AccountSync__c.field-meta.xml
<CustomField>
    <fullName>On_Demand_AccountSync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to control sync behavior when On-Demand mode is enabled in settings.</description>
    <label>On-Demand AccountSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/AccountSync_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls the Account synchronization process between Salesforce organizations. This setting determines whether synchronization is enabled or disabled.</description>
    <label>AccountSync Settings</label>
</CustomObject>

force-app/main/default/objects/AccountSync_Settings__c/fields/Endpoint_Path__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Path__c</fullName>
    <description>Defines the API endpoint path used for account synchronization requests.</description>
    <label>Endpoint Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether Account synchronization is currently active. If set to true, synchronization between Salesforce organizations is enabled.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Specifies the Named Credential API name used for authentication when making AccountSync API requests.</description>
    <label>Named Credential Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/fields/On_Demand_Mode__c.field-meta.xml
<CustomField>
    <fullName>On_Demand_Mode__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Controls whether account synchronization is enabled by default or only triggered manually.</description>
    <inlineHelpText>If enabled, accounts will not be synchronized automatically. Sync must be triggered manually or through specific user actions.
Disable this to sync all accounts by default.</inlineHelpText>
    <label>Enable Sync On Demand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/fields/Query_Endpoint_Path__c.field-meta.xml
<CustomField>
    <fullName>Query_Endpoint_Path__c</fullName>
    <description>Relative path used for SOQL query callout to external organization.</description>
    <label>Query Endpoint Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSync_Settings__c/fields/Record_Types_to_Sync__c.field-meta.xml
<CustomField>
    <fullName>Record_Types_to_Sync__c</fullName>
    <description>This field defines which Record Types should be included in the synchronization process. It allows specifying multiple record types that the system should consider when executing data synchronization operations.</description>
    <inlineHelpText>Specify the Record Type Developer Names that should be synchronized. Use a semicolon (;) to separate multiple values.

Example: Provider;Patient;Facility</inlineHelpText>
    <label>Record Types to Sync</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sync_Log__c/Sync_Log__c.object-meta.xml
<CustomObject>
    <description>APAL VMAP Sycn Logs</description>
    <label>Sync Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Sync Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sync_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Sync Status
In Process = New
Complete = Closed/Finish
Retry =  Run Retry attempts
Failed = Stop</description>
    <inlineHelpText>Sync Status
In Process = New
Complete = Closed/Finish
Retry =  Run Retry attempts
Failed = Stop</inlineHelpText>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountSyncBatchTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest
private class AccountSyncBatchTest {

    @TestSetup
    private static void testSetup() {
        insert new AccountSync_Settings__c(
                Name = 'Default Account Sync setting',
                Is_Active__c = true,
                Endpoint_Path__c = 'services/apexrest/AccountSync',
                Query_Endpoint_Path__c = '/services/data/v60.0/query?q=',
                Named_Credential__c = 'APAL_Org_Auth',
                On_Demand_Mode__c = true,
                Record_Types_to_Sync__c = 'Provider'
        );
    }
    @IsTest
    private static void accountSyncBatchExecuteTest() {
        Id personAccountRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Provider' LIMIT 1].Id;
        Account testAccountRecord = new Account(
                FirstName = 'Test',
                LastName = 'Account',
                Phone = '123-456-7890',
                On_Demand_AccountSync__c = true,
                RecordTypeId = personAccountRecordTypeId
        );

        Test.setMock(HttpCalloutMock.class, new AccountSyncCalloutMock());

        Test.startTest();

        Test.enableChangeDataCapture();

        insert testAccountRecord;

        Test.getEventBus().deliver();

        Test.stopTest();

        AsyncApexJob accountSyncBatchJob = [
                SELECT
                        Id
                        , Status
                        , ApexClass.Name
                        , JobType
                FROM AsyncApexJob
                ORDER BY CreatedDate DESC
                LIMIT 1
        ];

        Sync_Log__c syncLog = [SELECT Id, Status__c FROM Sync_Log__c LIMIT 1];
        String LOG_STATUS_COMPLETE = 'Complete';
        System.assertEquals(
                AccountSyncLogger.LOG_STATUS_COMPLETE,
                syncLog.Status__c,
                'Sync_Log__c record status should be Complete'
        );

        System.assertEquals(
                'Completed',
                accountSyncBatchJob.Status,
                'Status of the batch job should be completed'
        );
        System.assertEquals(
                'BatchApex',
                accountSyncBatchJob.JobType,
                'Job type should be BatchApex'
        );
        System.assertEquals(
                'AccountSyncBatch',
                accountSyncBatchJob.ApexClass.Name,
                'Batch job apex class name should be AccountSyncBatch'
        );
    }

    @IsTest
    private static void accountSyncBatchExecuteExceptionTest() {
        Id personAccountRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Provider' LIMIT 1].Id;
        Account testAccountRecord = new Account(
                FirstName = 'Test',
                LastName = 'Account',
                Phone = '123-456-7890',
                On_Demand_AccountSync__c = true,
                RecordTypeId = personAccountRecordTypeId
        );

        Test.startTest();

        Test.enableChangeDataCapture();

        insert testAccountRecord;

        Test.getEventBus().deliver();

        Test.stopTest();

        AsyncApexJob accountSyncBatchJob = [
                SELECT
                        Id
                        , Status
                        , ApexClass.Name
                        , JobType
                FROM AsyncApexJob
                ORDER BY CreatedDate DESC
                LIMIT 1
        ];

        Sync_Log__c syncLog = [SELECT Id, Status__c FROM Sync_Log__c LIMIT 1];
        String LOG_STATUS_FAILED = 'Failed';
        System.assertEquals(
                AccountSyncLogger.LOG_STATUS_FAILED,
                syncLog.Status__c,
                'Sync_Log__c record status should be Failed'
        );

        System.assertEquals(
                'Completed',
                accountSyncBatchJob.Status,
                'Status of the batch job should be completed'
        );
        System.assertEquals(
                'BatchApex',
                accountSyncBatchJob.JobType,
                'Job type should be BatchApex'
        );
        System.assertEquals(
                'AccountSyncBatch',
                accountSyncBatchJob.ApexClass.Name,
                'Batch job apex class name should be AccountSyncBatch'
        );
    }

    public class AccountSyncCalloutMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"test":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }
}