force-app/main/default/objects/AccountSync_Field_Mapping__mdt/AccountSync_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Defines the mapping configuration for Account fields between APAL and VMAP organizations. Only fields specified in this mapping will be considered for synchronization.</description>
    <label>AccountSync Field Mapping</label>
    <pluralLabel>AccountSync Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountSync_Field_Mapping__mdt/fields/APAL_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>APAL_Field_API_Name__c</fullName>
    <description>The API name of the Account field in the APAL org that will be mapped for synchronization.</description>
    <inlineHelpText>The API name of the corresponding Account field in the APAL org that will receive synchronized data from the VMAP org.</inlineHelpText>
    <label>APAL Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountSync_Field_Mapping__mdt/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <description>Specifies the default value for the mapped field in case the incoming data does not contain a value. This ensures data consistency and prevents null values during synchronization.</description>
    <label>Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSync_Field_Mapping__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether this field mapping is active for synchronization. If set to true, this mapping will be used.</description>
    <inlineHelpText>Determines whether this field mapping is active. If enabled, this mapping will be used during synchronization. If disabled, this field will be ignored.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountSync_Field_Mapping__mdt/fields/VMAP_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>VMAP_Field_API_Name__c</fullName>
    <description>The API name of the Account field in the VMAP org that will be mapped for synchronization.</description>
    <inlineHelpText>The API name of the corresponding Account field in the VMAP org that will send data to the APAL org during synchronization.</inlineHelpText>
    <label>VMAP Field API Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AccountSyncFieldMappingSelector.cls
/**
 * @author Artem Shevchenko
 * @date 02.26.2025
 *
 * @description Selector class for querying AccountSync_Field_Mapping__mdt records.
 */
public with sharing class AccountSyncFieldMappingSelector {

    /**
     * @description Retrieves all active field mapping records.
     * @return A list of active AccountSync_Field_Mapping__mdt metadata records.
    */
    public List<AccountSync_Field_Mapping__mdt> queryAllActive() {
        return [
                SELECT
                        Id
                        , APAL_Field_API_Name__c
                        , VMAP_Field_API_Name__c
                        , Default_Value__c
                FROM AccountSync_Field_Mapping__mdt
                WHERE Is_Active__c = TRUE
        ];
    }
}